apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-ingress
  namespace: istio-ingress
spec:
  interval: 1m
  dependsOn:
  - name: istio-base
    namespace: istio-system
  - name: istiod
    namespace: istio-system
  chart:
    spec:
      chart: istio-ingress
      version: "1.20.0"
      sourceRef:
        kind: HelmRepository
        name: istio/gateway
        namespace: istio-system
