apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tools
  namespace: flux-system
spec:
  prune: true
  force: true
  interval: 1m0s
  path: ./tools/
  sourceRef:
    kind: GitRepository
    name: flux-system