apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: servicey
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./apps/servicey
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 2m