apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: istio
  namespace: flux-system
spec:
  interval: 3m0s
  path: ./tools/istio
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 2m