apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tls
  namespace: flux-system
spec:
  interval: 3m0s
  path: ./tools/tls
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 2m
  dependsOn:
    - name: istio